<?php

/**
 * @file
 * The islandora_managed_access moudule.
 */

/**
 * Implements hook_menu().
 */
function islandora_managed_access_menu() {
}

/**
 * Implements hook_entity_info().
 */
function islandora_managed_access_entity_info() {
  $info = array();

  $info['managed_access_profile'] = array(
    'label' => t('Managed Access Profile'),
    'base table' => 'islandora_managed_access_profile',
    'entity keys' => array(
      'id' => 'id',
    ),
  );
  $info['managed_access_object'] = array(
    'label' => t('Managed Access Object'),
    'base table' => 'islandora_managed_access_object',
    'entity keys' => array(
      'id' => 'id',
    ),
  );
  $info['managed_access_user'] = array(
    'label' => t('Managed Access User'),
    'base table' => 'islandora_managed_access_user',
    'entity keys' => array(
      'id' => 'id',
    ),
  );

  return $info;
}
